name: Gitlab Sync

on: [push, pull_request, create, delete]

jobs:
  sync:
    name: Gitlab Sync
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: action-pack/gitlab-sync@v3
      with:
        url: ${{ secrets.GITLAB_URL }}
        username: ${{ secrets.GITLAB_USERNAME }}
        # Personal access token from gitlab.com 
<<<<<<< HEAD
        token: ${{ secrets.GITLAB_TOKEN }}
=======
        token: ${{ secrets.GITLAB_TOKEN }}
>>>>>>> d1b83019bdd4bec379aab81a371eeb726d9a10a4
